# Generated by Django 2.2.4 on 2019-10-18 21:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fridgeManager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='food_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of food', max_length=50, unique=True)),
                ('duration', models.IntegerField(help_text='How long does this item stay good for?', validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to=fridgeManager.models.get_image_path)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fridgeManager.food_category')),
            ],
        ),
    ]
