# Generated by Django 2.2.6 on 2019-10-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridgeManager', '0002_fridge_fridgefooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgefooditem',
            name='quantity',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fridgefooditem',
            name='fridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridgeManager.Fridge'),
        ),
    ]
