# Generated by Django 2.2.6 on 2019-10-19 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridgeManager', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_item',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='food_item',
            name='image',
        ),
    ]
